---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: debian-8
  - name: debian-9
  - name: debian-10
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[acpi]
